---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBgFm4lAsKFxmNCdeXYStcBG1YPO7GeiHiKR6gTX14xMfn/zJ9N2KvYBkxcp/DtOSoHK7pnmwF6NoD11/biisYeYiA8Yzmdh366AW38U/u+cKm325atVIZGnElUa3xp2OAAsKo2RAmpUyPEmPl6HozXUwCRP3o9UXZVEkR2m/XkkvkrYHsAJ5SRPeJpCdPSfSZeAL/Dtvev3fxmB5twLfws7gA3nsb/1/h1gU922wt5o9ioGkS9tVKaauvelX6fPtkGSGKMeDPJWuxkPDwQIB7PwFilaJi/mQ2hMprriOyaLM1iASvXIPkNHeNUfKocopa1qghK94HMQuNB4ZV7LGJkrs/ROxBwhMBIk3qsDkhrjQa21ZPfwPLG91hnnTYRdaoBdZv3EsrW/HlnkyIqOVhZ+s45O29blnnEbr2zN6t0Ha8Lo0o/AuUomwVUpr7uUfkkyPSUa+PEk8zd2fhE1E+xZc6UMywZlZcN4pVmOMnLvBKyEqalU70GgvdihsmhQ7MS3JAb8otHO9N6bNv+hSimsygnxv2Zqc/5go7AB71fHKj6KSPiKppgdLc8arR2ifNCyFsub8N3DOlUvlh2TUq1fqVqyLgzYcLYVeu9rOWgpiGbHOo+QUwVNwOkrtPcZHhnoZG2PhxHNoLAaVOOjTanpUo5QSPYpgQ7WZ/9+BiOm2VDq6YjCl2zF41nmp9/pzDNHctEx2pwgNkYOe0DHFT2DEzaIv9fdHptRIAVqi+YN0sUsHWBNeiTqZSE3VSHWILO8m8U3w==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
