---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAbd8BsvhNFUawUa/gL3dXb2g4PGwWsX5ifvcK9BaD6aEXQwPc8zI06PR5Iopgt7hneJDqnQ1PGNAA2kOk6GrMBouUaj9iz4gBVRFE5QC3qlJUebzCJh8NB+7fuhIKmJvddCTf4lXKql8OcXZzTNMth40avqlJPokFC5Bdd0pMQBrWSMf/SgPCJu5po8S1dtAPuxZVDvB7RCXKb/Vt3AvqEzYUhfjdRxYeRgVJE3NRDKajekol/jgwJr1np5/yL4Z3F/Vffu1JnEQ4Hy09JHhfH7k8nBJ/9QPw0+GqgnUQltOp1XeppjmdIv4NGkECTmP6rYYUgWciFZuofrg35t6mw6pNzyEiqKzp55tZUl5YUN6lOv8+4BxSpuhlwWf0Uy/828aVToYNE6w+oBBuu95i6iq5HOtdPHcdbbNEAjLvJsVcgcw5gS41zsN88/hfsBYRdSsS7HPvUfwyD/xzZL8RGLLC9EdpyYz6G68HO+/nH0O7vmnhqAllDO8ZDaZ5h2KKcB+csxECPu0iT5CQnqzJ/YxK+FgNniUODD7gJgZ6AvLgAJZqZrqxRACK9xNDbRmd6MIgNDnd/QqFkq2R5E4fvchkDjJwcMc6MhBL+0/RnsqJb0ZzJrzcVTpqas3zLCfDCwzSO3MGdfrjCg2PfswUtRgTPRjudc7U6eMF6MhJuzJ4Om7YZxOnRoouCmjVRt37LCn21sVM1BMmZ6AtClotF/VvJHzOUDI3aq+StXPQIIjqtBf2HknaoddJSYiOpIBVmUxsavg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
