---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCy65lplIgsbswIW3Nl6gPA4s8Va6LWipDKjLInvGyHEBLUQ/ZoO3EyRPgnV5rsuEY4nuEKw3ugwcuZ2SJxa9XKfJl55/nu7BJhk8y9t035mYJ31ncOPZ0hdXSVT4ZRFz/iAMtdtWVbOIY4zKncoAt9Apzjt1OE8Q/3jwngEXppIltUeH9UNDVO0usLJzFHFpyiQZut2+8jKjdw58O0pqSZNDes9i0TRQP4kwYcg2unxqNTo9DnFZdAsFJFa/7TFNQlVUUzwCwNbXwlKiglMXR4tS/pkdmGFfCC+dE5+WCvyGhCARX46mDXKNcb/uJgQlcqxe4xbBaobmnhwHUr6PEId+tIxlhIk0x8tITLQ7M8VPJnujchb05iRjEBFFHj0yZzDFJlovnQyCWsJrbv22J+PjupErvVJoKYr7Y8LH60q/NCJGJib6nixrnle28EHbGgxtRJx9amK6e0gpBS6DRO6gX9kqWXX6a+5oTq5NPSdHlKn1Vp2ilwx+nXZezy5qTbsvLmlTkESK/X3QSKAKnh2ob3tMYiznLV3H6yvzrKD5+UzS1KWaXnH17idvRPzlAPxLdmU9C7GBd3OGmJEBaGp2jjAKrsN+EXx9QcfqZgCb7AgnVj2VVFYTdRP3/16BxN39j1Dnh/zfpo9L7ESfrrOn72btvF5ZUD5uGSKuNHToT+WDupzufRWcSxOhlturgcw6C1lDqIsgksQecSLPtwttJAwQ3Ey2h7c/prAXzY3kIGMgZgidhBri2tMIspBgD/8g077g==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
