apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Replace this URL with your actual GitHub repository URL after you push
    repoURL: https://github.com/Franion03/arr-stack.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
