apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager/
  - storage/
  - prowlarr/
  - sonarr/
  - radarr/
  - transmission/
  - jellyfin/
  - jellyseerr/
  - homarr/
  - kubernetes-dashboard/
  - dispatcharr/
  - cloudflared/
  - assistant/
  - health/
