---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel-token
  namespace: media
spec:
  encryptedData:
    token: AgCUTRh2cnaLnQtr1TpVqwo/FJsbBsOO1wL1a40WO+W/hPTe49ussT8xR+xkqluh3Rg+xGam4EXNwpkl6Y0FUJitURdVRJHXzSUhYX0CwfTI2dSlxpuWpLCy1jS8iSfhS+xi2i9zxPNvnB+7//z/vwz1oJyvgKt7kk/7TkPiACVvI9r793IbtzEnup0BdKwY6B3gaaR6ip1V67YDsC857FTqD6BePs6deompPBJDAgaAD+1Ip6ZcTSNDXI+a7FupvEdLK+PxyQYcXjA41AKPZVSFJ3J5GTvBcaAnXMBv3XnXioKJUN/Tj5nyIeCV9UKzjPI9naECd1EOM60dvjEQNyspmixIqOMJSOpjrnhGX4IC8nEaBnu74qIlRbR9OLYsHjEYmlL5JBVolBc5FTgD45bx6zamGuk9xg8yOTMmvfrP+FShFGfbexKV1zqmDE/c0KLNBowkj23598viCEyzH3CqQHuV0iVWAfR8zn4tJYE9yA4R6LP3TdqyzLTNyQinMeM3NRwMAA1FCg6PzvJzNptLqH2LR6GjcmT30TarOIc4XLLJDsmStLd82ugGJ7GXYjF0xxExaU7SududYxF52VhLYAKEUbOWyaplXsi5gUnAFKQlSMtDOdzekkuWdqEebl6Y0cdAAr7agr7IcpW1up3UYgdeKEr4T1b/dtb0hsCCBUaqo6LbZBQQjjIZPVANuWZ1dEFjdkWOoBMku2MXgysLwQYP5JsiecNN5DFbIx1E7Vzgwg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel-token
      namespace: media
